### ISSUE TITLE
As a user directed to vote.usa.gov when I click on a button indicating my desire to register to vote, I want to choose my state as quickly as possible with minimal distractions.

### ISSUE THREAD

**Issue by jwbowers** [18F/vote-2016#1]
This issue represents the design audit of the pif created vote.usa.gov site. The content audit discussion is happening on [a Google Doc](https://docs.google.com/document/d/1tfJ4uMsIJC1DG3KWvkYc5oSBSO-WQXstkkzBJHf9s-Q/edit#)

I propose the following:

1. Get rid of the animated words. Leaving only the sentence about "Joining.."
2. Change the background picture to a simple solid color aligned with the Web Design Standards.
3. Delete as much of the content below the fold as possible.

**Comment by rogeruiz** [comment]
Pinging @ericadeahl on this one so she can discuss the above proposals here.

**Comment by adamsfallen** [comment]
Also jumping in - at a glance, some of the proposed changes here (and in the content doc) run contrary to the lessons learned and tested in v.1 - recommend coordinating with PIF team (looping in @lukad03 ) before moving forward on any of these design revisions so as to not reverse progress made.

**Comment by carodew** [comment]
@adamsfallen @lukad03 I'd be interested in getting an overview of any user research you folks did previously, and possibly any documentation you're able to share about that.

**Comment by carodew** [comment]
Did I see a meeting invite for that come through? Or am I imagining things?

**Comment by jwbowers** [comment]
I feel like this has been done --- at least done in terms of the design stage. I will close this now. Let me know if this is not correct procedure.
