### ISSUE TITLE
As a user of the existing vote.usa.gov site, I should not be confused when icons are not links.

### ISSUE THREAD

**Issue by jwbowers** [18F/vote-2016#3]
We should add real links to this section or delete the section.

```
<section class="actions">
        <div class="content-container">
          <h1>Ways to Register</h1>
          <div class="row">
            <div class="col person">
              <img alt="US Flag" src="assets/images/clipboard.png">
              <h3>In Person</h2>
            </div>
            <div class="col mail">
              <img alt="US Flag" src="assets/images/mail.png">
              <h3>By Mail</h2>
            </div>
            <div class="col online">
              <img alt="US Flag" src="assets/images/online.png">
              <h3>Online</h2>
            </div>
          </div>
        </div>
      </section>
```

**Comment by rogeruiz** [comment]
I agree with this. Do we have links for these sections? I feel like this content may already exist on the `usa.gov` site

**Comment by jwbowers** [comment]
There is some discussion about this on the google doc. Basically, the “by mail” is one link (http://www.eac.gov/voter_resources/register_to_vote.aspx <http://www.eac.gov/voter_resources/register_to_vote.aspx>) but the other links depend on the state. So to add those links would be a heavier lift for this site given our goals for it.

**Comment by carodew** [comment]
Agreed, I'm recommending in my design notes to remove this section until and if we get content for this. 

I also think this content is in the wrong place in the interaction flow, given that we can't have that information until after a user selects a state.

**Comment by jwbowers** [comment]
Since the Design has been moved to Done, I think we have dealt with this issue. Closing now.
